:ON ERROR EXIT

-- This file is consumed by scripts/Generate-DatabaseScript.ps1.
-- Passwords are supplied to sqlcmd at runtime and are never stored here.

-- Required by SQL Server for filtered indexes generated by EF Core.
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

USE [master];
GO

IF SUSER_ID(N'devsu_customers_app') IS NULL
BEGIN
    CREATE LOGIN [devsu_customers_app]
        WITH PASSWORD = '$(CUSTOMERS_DB_PASSWORD)',
        CHECK_POLICY = ON,
        CHECK_EXPIRATION = OFF;
END
ELSE
BEGIN
    ALTER LOGIN [devsu_customers_app]
        WITH PASSWORD = '$(CUSTOMERS_DB_PASSWORD)';
END;
GO

IF SUSER_ID(N'devsu_accounts_app') IS NULL
BEGIN
    CREATE LOGIN [devsu_accounts_app]
        WITH PASSWORD = '$(ACCOUNTS_DB_PASSWORD)',
        CHECK_POLICY = ON,
        CHECK_EXPIRATION = OFF;
END
ELSE
BEGIN
    ALTER LOGIN [devsu_accounts_app]
        WITH PASSWORD = '$(ACCOUNTS_DB_PASSWORD)';
END;
GO

IF DB_ID(N'CustomersDb') IS NULL
BEGIN
    CREATE DATABASE [CustomersDb];
END;
GO

IF DB_ID(N'AccountsDb') IS NULL
BEGIN
    CREATE DATABASE [AccountsDb];
END;
GO

USE [CustomersDb];
GO

IF SCHEMA_ID(N'customers') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA [customers]');
END;
GO

IF DATABASE_PRINCIPAL_ID(N'devsu_customers_app') IS NULL
BEGIN
    CREATE USER [devsu_customers_app] FOR LOGIN [devsu_customers_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datareader', N'devsu_customers_app') = 1
BEGIN
    ALTER ROLE [db_datareader] DROP MEMBER [devsu_customers_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datawriter', N'devsu_customers_app') = 1
BEGIN
    ALTER ROLE [db_datawriter] DROP MEMBER [devsu_customers_app];
END;
GO

GRANT SELECT, INSERT, UPDATE, DELETE
    ON SCHEMA::[customers]
    TO [devsu_customers_app];
GO

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    IF SCHEMA_ID(N'customers') IS NULL EXEC(N'CREATE SCHEMA [customers];');
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    CREATE TABLE [customers].[People] (
        [Id] uniqueidentifier NOT NULL,
        [Name] nvarchar(100) NOT NULL,
        [Gender] nvarchar(20) NOT NULL,
        [Age] int NOT NULL,
        [Identification] nvarchar(20) NOT NULL,
        [Address] nvarchar(200) NOT NULL,
        [Phone] nvarchar(25) NOT NULL,
        CONSTRAINT [PK_People] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_People_Age] CHECK ([Age] >= 0 AND [Age] <= 130),
        CONSTRAINT [CK_People_Gender] CHECK ([Gender] IN ('Male', 'Female', 'Other'))
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    CREATE TABLE [customers].[Customers] (
        [Id] uniqueidentifier NOT NULL,
        [PasswordHash] nvarchar(512) NOT NULL,
        [IsActive] bit NOT NULL,
        [CreatedAtUtc] datetimeoffset(7) NOT NULL,
        [UpdatedAtUtc] datetimeoffset(7) NOT NULL,
        [DeletedAtUtc] datetimeoffset(7) NULL,
        [AggregateVersion] bigint NOT NULL,
        [RowVersion] rowversion NOT NULL,
        CONSTRAINT [PK_Customers] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_Customers_AggregateVersion] CHECK ([AggregateVersion] >= 1),
        CONSTRAINT [FK_Customers_People_Id] FOREIGN KEY ([Id]) REFERENCES [customers].[People] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    CREATE INDEX [IX_Customers_IsActive_DeletedAtUtc] ON [customers].[Customers] ([IsActive], [DeletedAtUtc]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    CREATE UNIQUE INDEX [UX_People_Identification] ON [customers].[People] ([Identification]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908141830_InitialCustomers'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908141830_InitialCustomers', N'8.0.22');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908172936_AddCustomerOutbox'
)
BEGIN
    CREATE TABLE [customers].[OutboxMessages] (
        [EventId] uniqueidentifier NOT NULL,
        [EventType] nvarchar(128) NOT NULL,
        [OccurredAtUtc] datetimeoffset(7) NOT NULL,
        [CorrelationId] nvarchar(128) NOT NULL,
        [AggregateId] uniqueidentifier NOT NULL,
        [AggregateVersion] bigint NOT NULL,
        [Payload] nvarchar(max) NOT NULL,
        [AttemptCount] int NOT NULL,
        [NextAttemptAtUtc] datetimeoffset(7) NOT NULL,
        [LastAttemptAtUtc] datetimeoffset(7) NULL,
        [PublishedAtUtc] datetimeoffset(7) NULL,
        [LeaseId] uniqueidentifier NULL,
        [LeasedUntilUtc] datetimeoffset(7) NULL,
        [LastError] nvarchar(2000) NULL,
        [RowVersion] rowversion NOT NULL,
        CONSTRAINT [PK_OutboxMessages] PRIMARY KEY ([EventId]),
        CONSTRAINT [CK_OutboxMessages_AggregateVersion] CHECK ([AggregateVersion] >= 1),
        CONSTRAINT [CK_OutboxMessages_AttemptCount] CHECK ([AttemptCount] >= 0)
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908172936_AddCustomerOutbox'
)
BEGIN
    CREATE INDEX [IX_OutboxMessages_Aggregate] ON [customers].[OutboxMessages] ([AggregateId], [AggregateVersion]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908172936_AddCustomerOutbox'
)
BEGIN
    EXEC(N'CREATE INDEX [IX_OutboxMessages_Pending] ON [customers].[OutboxMessages] ([PublishedAtUtc], [NextAttemptAtUtc], [LeasedUntilUtc]) WHERE [PublishedAtUtc] IS NULL');
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908172936_AddCustomerOutbox'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908172936_AddCustomerOutbox', N'8.0.22');
END;
GO

COMMIT;
GO

USE [AccountsDb];
GO

IF SCHEMA_ID(N'accounts') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA [accounts]');
END;
GO

IF DATABASE_PRINCIPAL_ID(N'devsu_accounts_app') IS NULL
BEGIN
    CREATE USER [devsu_accounts_app] FOR LOGIN [devsu_accounts_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datareader', N'devsu_accounts_app') = 1
BEGIN
    ALTER ROLE [db_datareader] DROP MEMBER [devsu_accounts_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datawriter', N'devsu_accounts_app') = 1
BEGIN
    ALTER ROLE [db_datawriter] DROP MEMBER [devsu_accounts_app];
END;
GO

GRANT SELECT, INSERT, UPDATE, DELETE
    ON SCHEMA::[accounts]
    TO [devsu_accounts_app];
GO

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    IF SCHEMA_ID(N'accounts') IS NULL EXEC(N'CREATE SCHEMA [accounts];');
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE TABLE [accounts].[CustomerProjections] (
        [CustomerId] uniqueidentifier NOT NULL,
        [Name] nvarchar(100) NOT NULL,
        [IsActive] bit NOT NULL,
        [IsDeleted] bit NOT NULL,
        [AggregateVersion] bigint NOT NULL,
        [UpdatedAtUtc] datetimeoffset(7) NOT NULL,
        [RowVersion] rowversion NOT NULL,
        CONSTRAINT [PK_CustomerProjections] PRIMARY KEY ([CustomerId]),
        CONSTRAINT [CK_CustomerProjections_AggregateVersion] CHECK ([AggregateVersion] >= 1),
        CONSTRAINT [CK_CustomerProjections_Status] CHECK (NOT ([IsActive] = 1 AND [IsDeleted] = 1))
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE TABLE [accounts].[InboxMessages] (
        [EventId] uniqueidentifier NOT NULL,
        [EventType] nvarchar(128) NOT NULL,
        [CorrelationId] nvarchar(128) NOT NULL,
        [AggregateId] uniqueidentifier NOT NULL,
        [AggregateVersion] bigint NOT NULL,
        [OccurredAtUtc] datetimeoffset(7) NOT NULL,
        [ProcessedAtUtc] datetimeoffset(7) NOT NULL,
        CONSTRAINT [PK_InboxMessages] PRIMARY KEY ([EventId]),
        CONSTRAINT [CK_InboxMessages_AggregateVersion] CHECK ([AggregateVersion] >= 1)
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE TABLE [accounts].[Accounts] (
        [Number] nvarchar(20) NOT NULL,
        [Type] nvarchar(16) NOT NULL,
        [InitialBalance] decimal(18,2) NOT NULL,
        [CurrentBalance] decimal(18,2) NOT NULL,
        [IsActive] bit NOT NULL,
        [CustomerId] uniqueidentifier NOT NULL,
        [CreatedAtUtc] datetimeoffset(7) NOT NULL,
        [UpdatedAtUtc] datetimeoffset(7) NOT NULL,
        [RowVersion] rowversion NOT NULL,
        CONSTRAINT [PK_Accounts] PRIMARY KEY ([Number]),
        CONSTRAINT [CK_Accounts_CurrentBalance] CHECK ([CurrentBalance] >= 0),
        CONSTRAINT [CK_Accounts_InitialBalance] CHECK ([InitialBalance] >= 0),
        CONSTRAINT [CK_Accounts_Number] CHECK ([Number] <> '' AND [Number] NOT LIKE '%[^0-9]%'),
        CONSTRAINT [CK_Accounts_Type] CHECK ([Type] IN ('Savings', 'Checking')),
        CONSTRAINT [FK_Accounts_CustomerProjections_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [accounts].[CustomerProjections] ([CustomerId]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE INDEX [IX_Accounts_CustomerId_IsActive] ON [accounts].[Accounts] ([CustomerId], [IsActive]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE INDEX [IX_CustomerProjections_Status] ON [accounts].[CustomerProjections] ([IsActive], [IsDeleted]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE INDEX [IX_InboxMessages_Aggregate] ON [accounts].[InboxMessages] ([AggregateId], [AggregateVersion]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    CREATE INDEX [IX_InboxMessages_ProcessedAtUtc] ON [accounts].[InboxMessages] ([ProcessedAtUtc]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908221334_InitialAccounts'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908221334_InitialAccounts', N'8.0.22');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909011613_AddAccountMovements'
)
BEGIN
    CREATE TABLE [accounts].[AccountMovements] (
        [Id] bigint NOT NULL IDENTITY,
        [AccountNumber] nvarchar(20) NOT NULL,
        [Type] nvarchar(16) NOT NULL,
        [Value] decimal(18,2) NOT NULL,
        [Balance] decimal(18,2) NOT NULL,
        [IdempotencyKey] nvarchar(128) COLLATE Latin1_General_100_BIN2 NOT NULL,
        [RequestFingerprint] char(64) NOT NULL,
        [OccurredAtUtc] datetimeoffset(7) NOT NULL,
        [CreatedAtUtc] datetimeoffset(7) NOT NULL,
        [UpdatedAtUtc] datetimeoffset(7) NOT NULL,
        [RowVersion] rowversion NOT NULL,
        CONSTRAINT [PK_AccountMovements] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_AccountMovements_Balance] CHECK ([Balance] >= 0),
        CONSTRAINT [CK_AccountMovements_Type] CHECK ([Type] IN ('Deposit', 'Withdrawal')),
        CONSTRAINT [CK_AccountMovements_Value] CHECK (([Type] = 'Deposit' AND [Value] > 0) OR ([Type] = 'Withdrawal' AND [Value] < 0)),
        CONSTRAINT [FK_AccountMovements_Accounts_AccountNumber] FOREIGN KEY ([AccountNumber]) REFERENCES [accounts].[Accounts] ([Number]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909011613_AddAccountMovements'
)
BEGIN
    CREATE INDEX [IX_AccountMovements_AccountNumber_OccurredAtUtc_Id] ON [accounts].[AccountMovements] ([AccountNumber], [OccurredAtUtc], [Id]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909011613_AddAccountMovements'
)
BEGIN
    CREATE UNIQUE INDEX [UX_AccountMovements_IdempotencyKey] ON [accounts].[AccountMovements] ([IdempotencyKey]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909011613_AddAccountMovements'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260909011613_AddAccountMovements', N'8.0.22');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909143607_AddAccountMovementCorrections'
)
BEGIN
    CREATE TABLE [accounts].[AccountMovementCorrections] (
        [Id] bigint NOT NULL IDENTITY,
        [MovementId] bigint NOT NULL,
        [PreviousType] nvarchar(16) NOT NULL,
        [PreviousValue] decimal(18,2) NOT NULL,
        [PreviousOccurredAtUtc] datetimeoffset(7) NOT NULL,
        [PreviousBalance] decimal(18,2) NOT NULL,
        [NewType] nvarchar(16) NOT NULL,
        [NewValue] decimal(18,2) NOT NULL,
        [NewOccurredAtUtc] datetimeoffset(7) NOT NULL,
        [NewBalance] decimal(18,2) NOT NULL,
        [Reason] nvarchar(500) NOT NULL,
        [CorrelationId] nvarchar(128) NOT NULL,
        [CorrectedAtUtc] datetimeoffset(7) NOT NULL,
        CONSTRAINT [PK_AccountMovementCorrections] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_AccountMovementCorrections_NewBalance] CHECK ([NewBalance] >= 0),
        CONSTRAINT [CK_AccountMovementCorrections_NewType] CHECK ([NewType] IN ('Deposit', 'Withdrawal')),
        CONSTRAINT [CK_AccountMovementCorrections_NewValue] CHECK (([NewType] = 'Deposit' AND [NewValue] > 0) OR ([NewType] = 'Withdrawal' AND [NewValue] < 0)),
        CONSTRAINT [CK_AccountMovementCorrections_PreviousBalance] CHECK ([PreviousBalance] >= 0),
        CONSTRAINT [CK_AccountMovementCorrections_PreviousType] CHECK ([PreviousType] IN ('Deposit', 'Withdrawal')),
        CONSTRAINT [CK_AccountMovementCorrections_PreviousValue] CHECK (([PreviousType] = 'Deposit' AND [PreviousValue] > 0) OR ([PreviousType] = 'Withdrawal' AND [PreviousValue] < 0)),
        CONSTRAINT [FK_AccountMovementCorrections_AccountMovements_MovementId] FOREIGN KEY ([MovementId]) REFERENCES [accounts].[AccountMovements] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909143607_AddAccountMovementCorrections'
)
BEGIN
    CREATE INDEX [IX_AccountMovementCorrections_MovementId_CorrectedAtUtc] ON [accounts].[AccountMovementCorrections] ([MovementId], [CorrectedAtUtc]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260909143607_AddAccountMovementCorrections'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260909143607_AddAccountMovementCorrections', N'8.0.22');
END;
GO

COMMIT;
GO
