:ON ERROR EXIT

-- This file is consumed by scripts/Generate-DatabaseScript.ps1.
-- Passwords are supplied to sqlcmd at runtime and are never stored here.

-- Required by SQL Server for filtered indexes generated by EF Core.
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

USE [master];
GO

IF SUSER_ID(N'devsu_customers_app') IS NULL
BEGIN
    CREATE LOGIN [devsu_customers_app]
        WITH PASSWORD = '$(CUSTOMERS_DB_PASSWORD)',
        CHECK_POLICY = ON,
        CHECK_EXPIRATION = OFF;
END
ELSE
BEGIN
    ALTER LOGIN [devsu_customers_app]
        WITH PASSWORD = '$(CUSTOMERS_DB_PASSWORD)';
END;
GO

IF SUSER_ID(N'devsu_accounts_app') IS NULL
BEGIN
    CREATE LOGIN [devsu_accounts_app]
        WITH PASSWORD = '$(ACCOUNTS_DB_PASSWORD)',
        CHECK_POLICY = ON,
        CHECK_EXPIRATION = OFF;
END
ELSE
BEGIN
    ALTER LOGIN [devsu_accounts_app]
        WITH PASSWORD = '$(ACCOUNTS_DB_PASSWORD)';
END;
GO

IF DB_ID(N'CustomersDb') IS NULL
BEGIN
    CREATE DATABASE [CustomersDb];
END;
GO

IF DB_ID(N'AccountsDb') IS NULL
BEGIN
    CREATE DATABASE [AccountsDb];
END;
GO

USE [CustomersDb];
GO

IF SCHEMA_ID(N'customers') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA [customers]');
END;
GO

IF DATABASE_PRINCIPAL_ID(N'devsu_customers_app') IS NULL
BEGIN
    CREATE USER [devsu_customers_app] FOR LOGIN [devsu_customers_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datareader', N'devsu_customers_app') = 1
BEGIN
    ALTER ROLE [db_datareader] DROP MEMBER [devsu_customers_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datawriter', N'devsu_customers_app') = 1
BEGIN
    ALTER ROLE [db_datawriter] DROP MEMBER [devsu_customers_app];
END;
GO

GRANT SELECT, INSERT, UPDATE, DELETE
    ON SCHEMA::[customers]
    TO [devsu_customers_app];
GO

-- <CUSTOMERS_MIGRATIONS>

USE [AccountsDb];
GO

IF SCHEMA_ID(N'accounts') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA [accounts]');
END;
GO

IF DATABASE_PRINCIPAL_ID(N'devsu_accounts_app') IS NULL
BEGIN
    CREATE USER [devsu_accounts_app] FOR LOGIN [devsu_accounts_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datareader', N'devsu_accounts_app') = 1
BEGIN
    ALTER ROLE [db_datareader] DROP MEMBER [devsu_accounts_app];
END;
GO

IF IS_ROLEMEMBER(N'db_datawriter', N'devsu_accounts_app') = 1
BEGIN
    ALTER ROLE [db_datawriter] DROP MEMBER [devsu_accounts_app];
END;
GO

GRANT SELECT, INSERT, UPDATE, DELETE
    ON SCHEMA::[accounts]
    TO [devsu_accounts_app];
GO

-- <ACCOUNTS_MIGRATIONS>
