// <auto-generated />
using System;
using Devsu.Customers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devsu.Customers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    partial class CustomersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devsu.Customers.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("UX_People_Identification");

                    b.ToTable("People", "customers", t =>
                        {
                            t.HasCheckConstraint("CK_People_Age", "[Age] >= 0 AND [Age] <= 130");

                            t.HasCheckConstraint("CK_People_Gender", "[Gender] IN ('Male', 'Female', 'Other')");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Devsu.Customers.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("Devsu.Customers.Domain.Entities.Person");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasIndex("IsActive", "DeletedAtUtc")
                        .HasDatabaseName("IX_Customers_IsActive_DeletedAtUtc");

                    b.ToTable("Customers", "customers", t =>
                        {
                            t.HasCheckConstraint("CK_People_Age", "[Age] >= 0 AND [Age] <= 130");

                            t.HasCheckConstraint("CK_People_Gender", "[Gender] IN ('Male', 'Female', 'Other')");

                            t.HasCheckConstraint("CK_Customers_AggregateVersion", "[AggregateVersion] >= 1");
                        });
                });

            modelBuilder.Entity("Devsu.Customers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Devsu.Customers.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Devsu.Customers.Domain.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
