<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devsu.Clientes.Application\Devsu.Clientes.Application.csproj" />
    <ProjectReference Include="..\Devsu.Clientes.Domain\Devsu.Clientes.Domain.csproj" />
  </ItemGroup>

</Project>
