// <auto-generated />
using System;
using Devsu.Accounts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devsu.Accounts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    partial class AccountsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accounts")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devsu.Accounts.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Number");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("IX_Accounts_CustomerId_IsActive");

                    b.ToTable("Accounts", "accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_CurrentBalance", "[CurrentBalance] >= 0");

                            t.HasCheckConstraint("CK_Accounts_InitialBalance", "[InitialBalance] >= 0");

                            t.HasCheckConstraint("CK_Accounts_Number", "[Number] <> '' AND [Number] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Accounts_Type", "[Type] IN ('Savings', 'Checking')");
                        });
                });

            modelBuilder.Entity("Devsu.Accounts.Domain.Entities.CustomerProjection", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("CustomerId");

                    b.HasIndex("IsActive", "IsDeleted")
                        .HasDatabaseName("IX_CustomerProjections_Status");

                    b.ToTable("CustomerProjections", "accounts", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerProjections_AggregateVersion", "[AggregateVersion] >= 1");

                            t.HasCheckConstraint("CK_CustomerProjections_Status", "NOT ([IsActive] = 1 AND [IsDeleted] = 1)");
                        });
                });

            modelBuilder.Entity("Devsu.Accounts.Infrastructure.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_InboxMessages_ProcessedAtUtc");

                    b.HasIndex("AggregateId", "AggregateVersion")
                        .HasDatabaseName("IX_InboxMessages_Aggregate");

                    b.ToTable("InboxMessages", "accounts", t =>
                        {
                            t.HasCheckConstraint("CK_InboxMessages_AggregateVersion", "[AggregateVersion] >= 1");
                        });
                });

            modelBuilder.Entity("Devsu.Accounts.Domain.Entities.Account", b =>
                {
                    b.HasOne("Devsu.Accounts.Domain.Entities.CustomerProjection", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
