<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devsu.Accounts.Application\Devsu.Accounts.Application.csproj" />
    <ProjectReference Include="..\Devsu.Accounts.Domain\Devsu.Accounts.Domain.csproj" />
  </ItemGroup>

</Project>
